/*

███████ ██    ██ ███████ ██  ██████  ███    ██ 
██      ██    ██ ██      ██ ██    ██ ████   ██ 
█████   ██    ██ ███████ ██ ██    ██ ██ ██  ██ 
██      ██    ██      ██ ██ ██    ██ ██  ██ ██ 
██       ██████  ███████ ██  ██████  ██   ████ 
                                               
    Fusion Ban System v1.1
    Easily ban people from your Roblox game
*/

// This is the server. Unless you know what you're doing, please do not edit this file.

const express = require("express");
const fs = require("fs");
const app = express();
const { port, secretKey } = require("./config.json")

app.get("/", (req, res) => {
    res.send("You're running Fusion! Nice! Now just implement the script into your game and you'll be good to go.")
})

app.get("/query/bans", (req, res) => {
    const user = req.query.user;
    let raw = fs.readFileSync("./bans.json");
    let jsonstuff = JSON.parse(raw);
    res.json({ User: user, UserBanned: jsonstuff.bans.filter(account => account.User === user).length > 0 });
});

app.get("/query/useradd", (req, res) => {
    const authentication = req.query.authentication
    const user = req.query.user
    if (authentication === secretKey) {
        const raw = fs.readFileSync('bans.json');
        var data = JSON.parse(raw);
        data.bans.push({ "User": `${user}`, "UserBanned": true });

        var dataString = JSON.stringify(data, null, 4);
        fs.writeFileSync("bans.json", dataString);
        console.log(`Request to ban user ${user} accepted`)
        res.json({success: true})
    } else {
        res.status(401)
        res.json({success: false, message: "Invalid token"})
    }
});


app.listen(port, () => {
    console.log(`Welcome to Fusion! Listening on port ${port}.`);
});
